## Customers Table

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("E:\Customers.xlsx")

### Explore

In [3]:
df.head(10)
df.describe(include='all')

,CustomerID,Customer First Name,Customer Last Name,Gender,Phone Number,Nationality,Email Address,Start Deal,City,Province,Level,Paid
count,1577,1577,1577,1577,1.577000e+03,1577,1577,1577,1577,1577,1577,1577.000000
unique,1577,271,533,2,NaN,6,1577,NaN,93,13,4,NaN
top,SC-20575,Muhamad,Almisri,Male,NaN,Saudi Arabia,saybanabunfis@email.com,NaN,Riyadh,Riyadh,V1,NaN
freq,1,266,16,1046,NaN,651,1,NaN,214,381,915,NaN
mean,NaN,NaN,NaN,NaN,5.491275e+08,NaN,NaN,2021-08-12 15:24:05.022193920,NaN,NaN,NaN,19903.836785
min,NaN,NaN,NaN,NaN,5.000075e+08,NaN,NaN,2021-01-01 00:00:00,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,5.234763e+08,NaN,NaN,2021-03-09 00:00:00,NaN,NaN,NaN,1789.699200
50%,NaN,NaN,NaN,NaN,5.490596e+08,NaN,NaN,2021-06-03 00:00:00,NaN,NaN,NaN,8046.694080
75%,NaN,NaN,NaN,NaN,5.741345e+08,NaN,NaN,2021-10-11 00:00:00,NaN,NaN,NaN,31806.867240
max,NaN,NaN,NaN,NaN,5.999595e+08,NaN,NaN,2024-07-26 00:00:00,NaN,NaN,NaN,150261.219578
std,NaN,NaN,NaN,NaN,2.879076e+07,NaN,NaN,NaN,NaN,NaN,NaN,25154.233987

In [4]:
df.isnull().sum()

CustomerID             0
Customer First Name    0
Customer Last Name     0
Gender                 0
Phone Number           0
Nationality            0
Email Address          0
Start Deal             0
City                   0
Province               0
Level                  0
Paid                   0
dtype: int64

### Feature Engineering — Customer Name & Paid Status

In [5]:
df["Customer Name"] = df["Customer First Name"] + " " + df["Customer Last Name"]

In [6]:
df.drop(columns=["Customer First Name","Customer Last Name"], inplace=True)
df

,CustomerID,Gender,Phone Number,Nationality,Email Address,Start Deal,City,Province,Level,Paid,Customer Name
0,SC-20575,Female,516000352,Saudi Arabia,saybanabunfis@email.com,2021-05-21,Riyadh,Riyadh,V1,10519.917261,Sayban Abunfis
1,KW-16570,Male,553319849,Saudi Arabia,dieaturkmany@email.com,2021-02-08,Al Qassim,Al Qassim,V1,26212.289851,Diea Turkmany
2,DP-13000,Female,511700595,United Arab Emirates,jawaheralrz@email.com,2021-01-04,Jeddah,Mecca,V2,62163.334248,Jawaher Alrz
3,TB-21250,Female,586073003,Saudi Arabia,katymuhamad@email.com,2021-08-25,Jazan,Jizan,V1,6793.911641,Katy Muhamad
4,PK-18910,Male,528335918,Egypt,alialkhayran@email.com,2021-04-04,Jazan,Jizan,V1,14621.603504,Ali Alkhayran
...,...,...,...,...,...,...,...,...,...,...,...
1572,MG-7875,Male,535858463,Saudi Arabia,samirmusur@email.com,2023-11-23,Al-Aflaj,Riyadh,V2,46.484800,Samir Musur
1573,CS-2490,Female,576101048,Saudi Arabia,rashaalmala@email.com,2022-01-22,Al Makhwah,Al Bahah,V3,901.816800,Rasha Almala
1574,TN-11040,Male,513000231,Saudi Arabia,muhamadzayd@email.com,2022-11-22,Al-Aflaj,Riyadh,V1,110.287700,Muhamad Zayd
1575,RA-9915,Male,566828033,Syria,ayhamalghan@email.com,2023-05-23,Badr Al Janoub,Najran,V1,167.102400,Ayham Alghan
1576,ME-8010,Female,540909917,Syria,linaalrrashid@email.com,2023-12-04,Hajrah,Al Bahah,V1,483.429000,Lina Alrrashid

In [7]:
def Paid_Status(row):
    if row["Paid"]>0:
        return "Paid"
    else:
        return "Not Paid"
df["Paid_Status"] = df.apply(Paid_Status, axis=1)
df

,CustomerID,Gender,Phone Number,Nationality,Email Address,Start Deal,City,Province,Level,Paid,Customer Name,Paid_Status
0,SC-20575,Female,516000352,Saudi Arabia,saybanabunfis@email.com,2021-05-21,Riyadh,Riyadh,V1,10519.917261,Sayban Abunfis,Paid
1,KW-16570,Male,553319849,Saudi Arabia,dieaturkmany@email.com,2021-02-08,Al Qassim,Al Qassim,V1,26212.289851,Diea Turkmany,Paid
2,DP-13000,Female,511700595,United Arab Emirates,jawaheralrz@email.com,2021-01-04,Jeddah,Mecca,V2,62163.334248,Jawaher Alrz,Paid
3,TB-21250,Female,586073003,Saudi Arabia,katymuhamad@email.com,2021-08-25,Jazan,Jizan,V1,6793.911641,Katy Muhamad,Paid
4,PK-18910,Male,528335918,Egypt,alialkhayran@email.com,2021-04-04,Jazan,Jizan,V1,14621.603504,Ali Alkhayran,Paid
...,...,...,...,...,...,...,...,...,...,...,...,...
1572,MG-7875,Male,535858463,Saudi Arabia,samirmusur@email.com,2023-11-23,Al-Aflaj,Riyadh,V2,46.484800,Samir Musur,Paid
1573,CS-2490,Female,576101048,Saudi Arabia,rashaalmala@email.com,2022-01-22,Al Makhwah,Al Bahah,V3,901.816800,Rasha Almala,Paid
1574,TN-11040,Male,513000231,Saudi Arabia,muhamadzayd@email.com,2022-11-22,Al-Aflaj,Riyadh,V1,110.287700,Muhamad Zayd,Paid
1575,RA-9915,Male,566828033,Syria,ayhamalghan@email.com,2023-05-23,Badr Al Janoub,Najran,V1,167.102400,Ayham Alghan,Paid
1576,ME-8010,Female,540909917,Syria,linaalrrashid@email.com,2023-12-04,Hajrah,Al Bahah,V1,483.429000,Lina Alrrashid,Paid

### Rename Columns — Replace Spaces with Underscores

In [8]:
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['CustomerID', 'Gender', 'Phone_Number', 'Nationality', 'Email_Address',
       'Start_Deal', 'City', 'Province', 'Level', 'Paid', 'Customer_Name',
       'Paid_Status'],
      dtype='object')

### Load to SQL Server — Customers

In [9]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\aly_2005\appdata\local\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\aly_2005\appdata\local\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\aly_2005\appdata\local\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\aly_2005\appdata\local\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
from sqlalchemy import create_engine
import pandas as pd

server   = r'DESKTOP-J0HPDNG\SQLEXPRESS'
database = 'Sales_Insights'
driver   = 'ODBC Driver 18 for SQL Server'

engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}?driver={driver.replace(' ', '+')}&trusted_connection=yes&TrustServerCertificate=yes"
)
pd.read_sql("SELECT GETDATE()", engine)

C:\Users\aly_2005\AppData\Local\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

0 2026-06-15 12:06:43.763

In [11]:
table_name = "Customers_Data"
df.to_sql(table_name, engine, if_exists="replace", index=False)
pd.read_sql("SELECT TOP 5 * FROM Customers_Data", engine)

,CustomerID,Gender,Phone_Number,Nationality,Email_Address,Start_Deal,City,Province,Level,Paid,Customer_Name,Paid_Status
0,SC-20575,Female,516000352,Saudi Arabia,saybanabunfis@email.com,2021-05-21,Riyadh,Riyadh,V1,10519.917261,Sayban Abunfis,Paid
1,KW-16570,Male,553319849,Saudi Arabia,dieaturkmany@email.com,2021-02-08,Al Qassim,Al Qassim,V1,26212.289851,Diea Turkmany,Paid
2,DP-13000,Female,511700595,United Arab Emirates,jawaheralrz@email.com,2021-01-04,Jeddah,Mecca,V2,62163.334248,Jawaher Alrz,Paid
3,TB-21250,Female,586073003,Saudi Arabia,katymuhamad@email.com,2021-08-25,Jazan,Jizan,V1,6793.911641,Katy Muhamad,Paid
4,PK-18910,Male,528335918,Egypt,alialkhayran@email.com,2021-04-04,Jazan,Jizan,V1,14621.603504,Ali Alkhayran,Paid

## Orders Table

In [12]:
df = pd.read_csv("E:\Orders.csv")

### Explore

In [13]:
df.describe(include='all')

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Product ID,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status
count,50860,50860,50860,50860,50860,50860,50860,50860,50860,50860,...,50860,50860,50860.000000,50860.000000,50860.000000,50860.000000,50856,50860,33442.000000,32298
unique,25234,1429,1463,2,4,1573,1492,3,93,13,...,10281,3788,NaN,NaN,NaN,NaN,10020,4,NaN,3
top,DR-2024-100111,18/6/2024,22/11/2024,Internal,Standard Class,PO-18850,Muhamad Almisri,Consumer,Riyadh,Riyadh,...,OFF-AR-10003651,Staples,NaN,NaN,NaN,NaN,0.71,Medium,NaN,Completed
freq,14,133,130,46729,30502,97,169,26306,10939,17225,...,35,225,NaN,NaN,NaN,NaN,75,29213,NaN,29849
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,246.639063,3.477861,0.142742,28.601154,NaN,NaN,4.000030,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,488.047913,2.276957,0.212137,174.602732,NaN,NaN,1.119314,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000,NaN,NaN,1.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,30.741750,2.000000,0.000000,0.000000,NaN,NaN,4.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,85.056000,3.000000,0.000000,9.240000,NaN,NaN,4.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,251.197450,5.000000,0.200000,36.810000,NaN,NaN,5.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,22638.480000,14.000000,0.850000,8399.976000,NaN,NaN,5.000000,NaN

In [14]:
df.isnull().sum()

Order ID                 0
Order Date               0
Ship Date                0
Internal/External        0
Ship Mode                0
Customer ID              0
Customer Name            0
Segment                  0
City                     0
Provice                  0
Market                   0
Product ID               0
Product Name             0
Sales                    0
Quantity                 0
Discount                 0
Profit                   0
Shipping Cost            4
Order Priority           0
Rating               17418
Status               18562
dtype: int64

In [15]:
df.dtypes

Order ID              object
Order Date            object
Ship Date             object
Internal/External     object
Ship Mode             object
Customer ID           object
Customer Name         object
Segment               object
City                  object
Provice               object
Market                object
Product ID            object
Product Name          object
Sales                float64
Quantity               int64
Discount             float64
Profit               float64
Shipping Cost         object
Order Priority        object
Rating               float64
Status                object
dtype: object

### Fix Shipping Cost — Convert to Numeric

In [16]:
df['Shipping Cost'] = pd.to_numeric(df['Shipping Cost'], errors='coerce')
print(df['Shipping Cost'].max(), df['Shipping Cost'].min())

987.41 0.0

### Fill Missing Values

In [17]:
df['Shipping Cost'].fillna(df['Shipping Cost'].mean(), inplace=True)
df['Status'].fillna('Pending', inplace=True)

C:\Users\aly_2005\AppData\Local\Temp\ipykernel_6268\675469604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Shipping Cost'].fillna(df['Shipping Cost'].mean(), inplace=True)
C:\Users\aly_2005\AppData\Local\Temp\ipykernel_6268\675469604.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Status'].fillna('Pending', inplace=True)

In [18]:
df.isnull().sum()

Order ID                 0
Order Date               0
Ship Date                0
Internal/External        0
Ship Mode                0
Customer ID              0
Customer Name            0
Segment                  0
City                     0
Provice                  0
Market                   0
Product ID               0
Product Name             0
Sales                    0
Quantity                 0
Discount                 0
Profit                   0
Shipping Cost            0
Order Priority           0
Rating               17418
Status                   0
dtype: int64

### Rename Columns — Replace Spaces with Underscores

In [19]:
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['Order_ID', 'Order_Date', 'Ship_Date', 'Internal/External', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'City', 'Provice', 'Market',
       'Product_ID', 'Product_Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Shipping_Cost', 'Order_Priority', 'Rating', 'Status'],
      dtype='object')

### Feature Engineering — Avg Rating by Category

In [20]:
df['Rating'] = df.groupby(df['Product_ID'].apply(lambda x: x.split('-')[0]))['Rating'].transform(lambda x: x.fillna(x.mean()))

### Feature Engineering — Net Profit

In [21]:
df['Net_Profit_B'] = df['Profit'] - df['Shipping_Cost']
df['Net_Profit_A'] = df['Net_Profit_B'] - (df['Net_Profit_B'] * df['Discount'])
df.head(20)

,Order_ID,Order_Date,Ship_Date,Internal/External,Ship_Mode,Customer_ID,Customer_Name,Segment,City,Provice,...,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Rating,Status,Net_Profit_B,Net_Profit_A
0,RY-2024-143658,2/10/2024,6/10/2024,Internal,Standard Class,SC-20575,Sayban Abunfis,Consumer,Riyadh,Riyadh,...,13.080,3,0.0,4.560,1.03,Medium,4.000000,Pending,3.530,3.5300
1,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,252.160,8,0.0,90.720,13.45,Medium,5.000000,Completed,77.270,77.2700
2,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,193.280,2,0.0,54.080,9.63,Medium,4.000000,Completed,44.450,44.4500
3,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,35.440,4,0.0,4.960,1.37,Medium,5.000000,Pending,3.590,3.5900
4,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,71.600,2,0.0,11.440,3.79,Medium,4.000000,Completed,7.650,7.6500
5,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,56.120,2,0.0,21.320,4.72,Medium,3.999021,Completed,16.600,16.6000
6,JD-2023-134096,27/9/2023,1/10/2023,Internal,Standard Class,DP-13000,Jawaher Alrz,Consumer,Jeddah,Mecca,...,56.120,2,0.0,21.320,4.11,Medium,4.000000,Completed,17.210,17.2100
7,JD-2023-134096,27/9/2023,1/10/2023,Internal,Standard Class,DP-13000,Jawaher Alrz,Consumer,Jeddah,Mecca,...,344.640,3,0.0,165.420,26.20,Medium,4.000000,Completed,139.220,139.2200
8,JD-2023-134096,27/9/2023,1/10/2023,Internal,Standard Class,DP-13000,Jawaher Alrz,Consumer,Jeddah,Mecca,...,97.360,4,0.0,19.440,6.86,Medium,3.999021,Pending,12.580,12.5800
9,JD-2023-134096,27/9/2023,1/10/2023,Internal,Standard Class,DP-13000,Jawaher Alrz,Consumer,Jeddah,Mecca,...,341.520,2,0.0,13.640,17.34,Medium,4.000000,Returned,-3.700,-3.7000
10,JD-2023-134096,27/9/2023,1/10/2023,Internal,Standard Class,DP-13000,Jawaher Alrz,Consumer,Jeddah,Mecca,...,12.060,3,0.0,3.480,1.13,Medium,4.000000,Pending,2.350,2.3500
11,JZ-2023-156335,5/3/2023,12/3/2023,Internal,Standard Class,TB-21250,Katy Muhamad,Consumer,Jazan,Jizan,...,20.760,3,0.0,9.540,0.65,Medium,5.000000,Completed,8.890,8.8900
12,JZ-2023-156335,5/3/2023,12/3/2023,Internal,Standard Class,TB-21250,Katy Muhamad,Consumer,Jazan,Jizan,...,210.640,4,0.0,50.480,16.07,Medium,4.000000,Pending,34.410,34.4100
13,JZ-2024-121923,24/9/2024,1/10/2024,Internal,Standard Class,PK-18910,Ali Alkhayran,Home Office,Jazan,Jizan,...,80.100,3,0.0,37.620,8.86,Low,3.999021,Completed,28.760,28.7600
14,JD-2024-135706,18/10/2024,23/10/2024,Internal,Standard Class,JK-15625,Lama Alnasar,Consumer,Jeddah,Mecca,...,132.640,4,0.0,35.760,6.20,Medium,3.000000,Pending,29.560,29.5600
15,JD-2024-135706,18/10/2024,23/10/2024,Internal,Standard Class,JK-15625,Lama Alnasar,Consumer,Jeddah,Mecca,...,12.940,1,0.0,1.020,0.46,Medium,4.000000,Pending,0.560,0.5600
16,DR-2023-126655,26/6/2023,1/7/2023,Internal,Standard Class,HE-14800,Muhamad Husu,Corporate,Ad Diriyah,Riyadh,...,18.840,2,0.4,-6.600,1.60,Medium,3.999021,Pending,-8.200,-4.9200
17,DR-2023-126655,26/6/2023,1/7/2023,Internal,Standard Class,HE-14800,Muhamad Husu,Corporate,Ad Diriyah,Riyadh,...,308.280,7,0.4,-149.100,27.77,Medium,4.000000,Pending,-176.870,-106.1220
18,DR-2023-126655,26/6/2023,1/7/2023,Internal,Standard Class,HE-14800,Muhamad Husu,Corporate,Ad Diriyah,Riyadh,...,40.176,2,0.4,-6.064,2.14,Medium,4.000000,Pending,-8.204,-4.9224
19,DR-2023-126655,26/6/2023,1/7/2023,Internal,Standard Class,HE-14800,Muhamad Husu,Corporate,Ad Diriyah,Riyadh,...,8.784,3,0.4,-4.836,0.38,Medium,5.000000,Completed,-5.216,-3.1296

### Load to SQL Server — Orders

In [22]:
from sqlalchemy import create_engine
import pandas as pd

server   = r'DESKTOP-J0HPDNG\SQLEXPRESS'
database = 'Sales_Insights'
driver   = 'ODBC Driver 18 for SQL Server'

engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}?driver={driver.replace(' ', '+')}&trusted_connection=yes&TrustServerCertificate=yes"
)

In [23]:
table_name = "Orders_Data"
df.to_sql(table_name, engine, if_exists="replace", index=False)
pd.read_sql("SELECT TOP 5 * FROM Orders_Data", engine)

C:\Users\aly_2005\AppData\Local\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

,Order_ID,Order_Date,Ship_Date,Internal/External,Ship_Mode,Customer_ID,Customer_Name,Segment,City,Provice,...,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Rating,Status,Net_Profit_B,Net_Profit_A
0,RY-2024-3626252,10/11/2024,15/11/2024,Internal,Standard Class,MH-17290,Muhamad Jalal,Home Office,Riyadh,Riyadh,...,693.198,6,0.10,253.998,43.29,Medium,5.000000,Completed,210.708,189.6372
1,FF-2023-5727837,2/9/2023,8/9/2023,Internal,Standard Class,CA-11965,Muhamad Alakhris,Corporate,Fayfa,Jizan,...,38.760,2,0.00,18.180,3.19,Medium,3.999021,Completed,14.990,14.9900
2,JB-2024-3563223,23/12/2024,27/12/2024,Internal,Standard Class,CP-12340,Ihsan Alkfrswsany,Corporate,Al Jubail,Eastern Province,...,300.720,8,0.00,18.000,19.58,Medium,4.000000,Pending,-1.580,-1.5800
3,JB-2024-3563223,23/12/2024,27/12/2024,Internal,Standard Class,CP-12340,Ihsan Alkfrswsany,Corporate,Al Jubail,Eastern Province,...,182.898,1,0.10,42.648,24.91,Medium,4.000000,Pending,17.738,15.9642
4,RY-2024-3604759,3/4/2024,7/4/2024,Internal,Standard Class,SJ-20125,Muhamad Alnasar,Home Office,Riyadh,Riyadh,...,1599.156,6,0.15,37.476,170.95,High,3.986227,Pending,-133.474,-113.4529